[package]
name = "talaria-tui"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
parking_lot = { workspace = true }
ratatui = { workspace = true }
chrono = { workspace = true }
crossbeam-channel = "0.5.15"
opencv = "0.98.0"
thiserror = { workspace = true }
